AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >

    Endpoint for alexa-ping skill

    Author: Barnaby Shearer <b@Zi.iS>

Outputs:

    PingFunction:
      Description: "Lambda Function ARN"
      Value: !GetAtt PingFunction.Arn

Resources:

    PingServiceIAMRole:
        Type: "AWS::IAM::Role"
        Properties:
            Path: "/"
            ManagedPolicyArns:
                - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
            AssumeRolePolicyDocument:
              Version: "2012-10-17"
              Statement:
                -
                  Sid: "AllowLambdaServiceToAssumeRole"
                  Effect: "Allow"
                  Action: 
                    - "sts:AssumeRole"
                  Principal:
                    Service: 
                      - "lambda.amazonaws.com"

    PingFunction:
      Type: 'AWS::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: nodejs6.10
        CodeUri: index.js
        Role: !GetAtt PingServiceIAMRole.Arn
        Events:
            AlexaSkillEvent:
                Type: AlexaSkill
